### YamlMime:ManagedReference
items:
- uid: NuvTools.Notification.Mail.Configuration
  commentId: N:NuvTools.Notification.Mail.Configuration
  id: NuvTools.Notification.Mail.Configuration
  children:
  - NuvTools.Notification.Mail.Configuration.MailConfigurationSection
  - NuvTools.Notification.Mail.Configuration.ServiceCollectionExtensions
  langs:
  - csharp
  - vb
  name: NuvTools.Notification.Mail.Configuration
  nameWithType: NuvTools.Notification.Mail.Configuration
  fullName: NuvTools.Notification.Mail.Configuration
  type: Namespace
  assemblies:
  - NuvTools.Notification.Mail
references:
- uid: NuvTools.Notification.Mail.Configuration.MailConfigurationSection
  commentId: T:NuvTools.Notification.Mail.Configuration.MailConfigurationSection
  isExternal: true
  href: NuvTools.Notification.Mail.Configuration.MailConfigurationSection.html
  name: MailConfigurationSection
  nameWithType: MailConfigurationSection
  fullName: NuvTools.Notification.Mail.Configuration.MailConfigurationSection
- uid: NuvTools.Notification.Mail.Configuration.ServiceCollectionExtensions
  commentId: T:NuvTools.Notification.Mail.Configuration.ServiceCollectionExtensions
  isExternal: true
  href: NuvTools.Notification.Mail.Configuration.ServiceCollectionExtensions.html
  name: ServiceCollectionExtensions
  nameWithType: ServiceCollectionExtensions
  fullName: NuvTools.Notification.Mail.Configuration.ServiceCollectionExtensions
