### YamlMime:ManagedReference
items:
- uid: NuvTools.Security
  commentId: N:NuvTools.Security
  id: NuvTools.Security
  children:
  - NuvTools.Security.HasPermissionAttribute`1
  - NuvTools.Security.PermissionsOptions
  langs:
  - csharp
  - vb
  name: NuvTools.Security
  nameWithType: NuvTools.Security
  fullName: NuvTools.Security
  type: Namespace
  assemblies:
  - NuvTools.Security
references:
- uid: NuvTools.Security.HasPermissionAttribute`1
  commentId: T:NuvTools.Security.HasPermissionAttribute`1
  isExternal: true
  href: NuvTools.Security.HasPermissionAttribute-1.html
  name: HasPermissionAttribute<TEnum>
  nameWithType: HasPermissionAttribute<TEnum>
  fullName: NuvTools.Security.HasPermissionAttribute<TEnum>
  nameWithType.vb: HasPermissionAttribute(Of TEnum)
  fullName.vb: NuvTools.Security.HasPermissionAttribute(Of TEnum)
  name.vb: HasPermissionAttribute(Of TEnum)
  spec.csharp:
  - uid: NuvTools.Security.HasPermissionAttribute`1
    name: HasPermissionAttribute
    isExternal: true
    href: NuvTools.Security.HasPermissionAttribute-1.html
  - name: <
  - name: TEnum
  - name: '>'
  spec.vb:
  - uid: NuvTools.Security.HasPermissionAttribute`1
    name: HasPermissionAttribute
    isExternal: true
    href: NuvTools.Security.HasPermissionAttribute-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TEnum
  - name: )
- uid: NuvTools.Security.PermissionsOptions
  commentId: T:NuvTools.Security.PermissionsOptions
  isExternal: true
  href: NuvTools.Security.PermissionsOptions.html
  name: PermissionsOptions
  nameWithType: PermissionsOptions
  fullName: NuvTools.Security.PermissionsOptions
