### YamlMime:ManagedReference
items:
- uid: NuvTools.Security.AspNetCore.Configuration
  commentId: N:NuvTools.Security.AspNetCore.Configuration
  id: NuvTools.Security.AspNetCore.Configuration
  children:
  - NuvTools.Security.AspNetCore.Configuration.SecurityConfigurationSection
  - NuvTools.Security.AspNetCore.Configuration.ServiceCollectionExtensions
  langs:
  - csharp
  - vb
  name: NuvTools.Security.AspNetCore.Configuration
  nameWithType: NuvTools.Security.AspNetCore.Configuration
  fullName: NuvTools.Security.AspNetCore.Configuration
  type: Namespace
  assemblies:
  - NuvTools.Security.AspNetCore
references:
- uid: NuvTools.Security.AspNetCore.Configuration.SecurityConfigurationSection
  commentId: T:NuvTools.Security.AspNetCore.Configuration.SecurityConfigurationSection
  isExternal: true
  href: NuvTools.Security.AspNetCore.Configuration.SecurityConfigurationSection.html
  name: SecurityConfigurationSection
  nameWithType: SecurityConfigurationSection
  fullName: NuvTools.Security.AspNetCore.Configuration.SecurityConfigurationSection
- uid: NuvTools.Security.AspNetCore.Configuration.ServiceCollectionExtensions
  commentId: T:NuvTools.Security.AspNetCore.Configuration.ServiceCollectionExtensions
  isExternal: true
  href: NuvTools.Security.AspNetCore.Configuration.ServiceCollectionExtensions.html
  name: ServiceCollectionExtensions
  nameWithType: ServiceCollectionExtensions
  fullName: NuvTools.Security.AspNetCore.Configuration.ServiceCollectionExtensions
